apiVersion: v1
kind: Service
metadata:
  name: slackbot-workout
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: slackbot-workout
  type: LoadBalancer